title: Arduino Latest
description: Get the latest version of Arduino IDE programmatically!
author: Simone Primarosa
logo: /arcuino-cli.png
theme: jekyll-theme-tactile
show_stargazers: true
exclude:
- CODE_OF_CONDUCT.md
- LICENSE
- README.md
- _config.yml
gems:
  - jekyll-seo-tag
  - jekyll-sitemap
google_site_verification: IaHL0xooF4eo0ktwg5FNjhYpE3Fx2JWOWFVaJNzABJ4
google_analytics:
