---
name: Arduino Latest
description: Get the latest version of Arduino IDE programmatically!
theme: jekyll-theme-tactile
exclude:
- CODE_OF_CONDUCT.md
- LICENSE
- README.md
- _config.yml
sass:
  style: :compressed
  sass_dir: _css
